name: Deploy to GitHub Pages

on:
  workflow_dispatch: # Позволяет запускать workflow вручную через интерфейс GitHub
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./project2

      - name: Build project
        run: npm run build
        working-directory: ./project2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./project2/dist # Укажите путь к папке со статическими файлами
